KAME2: XRecursiveRWLock Class Reference
XRecursiveRWLock Class Reference
#include <rwlock.h>
Detailed Description
fully recursive read-write lock writeLock/Unlock inside readLock/Unlock routine is allowed
Definition at line 65 of file rwlock.h.
Public Member Functions
void readLock () const
void readUnlock () const
must unlock with the locking thread
bool tryWriteLock ()
void writeLock ()
bool writeUnlock ()
bool writeUnlockNReadLock ()
bool isLocked () const
ReadLocked or WriteLocked.
Private Types
typedef std::deque< const
XRecursiveRWLock * > tLockedList
typedef tLockedList::iterator tLockedList_it
Private Member Functions
bool _writeLock (bool trylock)
Private Attributes
pthread_cond_t m_cond
pthread_mutex_t m_mutex_write
mutex for condition and m_rdlockingcnt
int m_wrlockwaitingcnt
int m_rdlockingcnt
int m_wrlockingcnt
threadid_t m_wrlockingthread
Static Private Attributes
static XThreadLocal< tLockedList > s_tlRdLockedList
Member Function Documentation
bool XRecursiveRWLock::tryWriteLock ()
Returns:
true if locked.
Definition at line 179 of file rwlock.cpp.
Referenced by XDriver::tryStartRecording().
bool XRecursiveRWLock::writeUnlock ()
true if unlocked must unlock with the locking thread
Definition at line 189 of file rwlock.cpp.
References m_mutex_write.
Referenced by XDriver::abortRecording(), XGraph::unlock(), and XWaveNGraph::writeUnlock().
The documentation for this class was generated from the following files:
kame/rwlock.h
kame/rwlock.cpp