KAME2: XSecondaryDriver Class Reference
XSecondaryDriver Class Reference
#include <secondarydriver.h>
Detailed Description
Base class for all instrument drivers.
Definition at line 21 of file secondarydriver.h.
Public Member Functions
virtual void showForms ()=0
show all forms belonging to driver
virtual const shared_ptr
< XRecordDependency > dependency () const
Protected Member Functions
XSecondaryDriver (const char *name, bool runtime, const shared_ptr< XScalarEntryList > &scalarentries, const shared_ptr< XInterfaceList > &interfaces, const shared_ptr< XThermometerList > &thermometers, const shared_ptr< XDriverList > &drivers)
void connect (const shared_ptr< XItemNodeBase > &item, bool check_deep_dep=true)
call this to receive signal/data
void requestAnalysis ()
void unlockConnection (const shared_ptr< XDriver > &connected)
unlock one of connections in order to change the state of that instrument.
virtual void analyze (const shared_ptr< XDriver > &emitter)=0 throw (XRecordError&)
virtual void visualize ()=0
virtual bool checkDependency (const shared_ptr< XDriver > &emitter) const =0
virtual void start ()
usually nothing to do
virtual void stop ()
usually nothing to do
Private Types
typedef std::vector
< shared_ptr< const XDriver >
>::const_iterator tConnection_it
Private Member Functions
void readLockAllConnections ()
void readUnlockAllConnections ()
bool checkDeepDependency (shared_ptr< XRecordDependency > &) const
true if dependency is resolved
void onConnectedRecorded (const shared_ptr< XDriver > &)
void beforeItemChanged (const shared_ptr< XValueNodeBase > &item)
void onItemChangedCheckDeepDep (const shared_ptr< XValueNodeBase > &item)
void onItemChanged (const shared_ptr< XValueNodeBase > &item)
Private Attributes
shared_ptr< XRecordDependency > m_dependency
std::vector< shared_ptr< const
XDriver > > m_connections
holds connections
std::vector< shared_ptr< const
XDriver > > m_connections_check_deep_dep
XRWLock m_connection_mutex
shared_ptr< XListener > m_lsnOnRecord
shared_ptr< XListener > m_lsnBeforeItemChanged
shared_ptr< XListener > m_lsnOnItemChangedCheckDeepDep
shared_ptr< XListener > m_lsnOnItemChanged
Member Function Documentation
void XSecondaryDriver::requestAnalysis () [protected]
check dependencies and lock all records and analyze null pointer will be passed to analyze() emitter is driver itself.
See also:
analyze(), checkDependency()
Definition at line 85 of file secondarydriver.cpp.
References onConnectedRecorded().
virtual void XSecondaryDriver::analyze (const shared_ptr< XDriver > & emitter) throw (XRecordError&) [protected, pure virtual]
this is called when connected driver emit a signal unless dependency is broken all connected drivers are readLocked
Implemented in XNMRT1.
Referenced by onConnectedRecorded().
virtual void XSecondaryDriver::visualize () [protected, pure virtual]
this is called after analyze() or analyzeRaw() record is readLocked this must be reentrant unlike analyze()
Implements XDriver.
Implemented in XNMRT1.
Referenced by onConnectedRecorded().
virtual bool XSecondaryDriver::checkDependency (const shared_ptr< XDriver > & emitter) const [protected, pure virtual]
check connected drivers have valid time
Returns:
true if dependency is resolved this must be reentrant unlike analyze()
Implemented in XNMRT1.
Referenced by onConnectedRecorded().
void XSecondaryDriver::onConnectedRecorded (const shared_ptr< XDriver > & driver) [private]
called by connected drivers does dependency checks, readLock all connected drivers, write and finally call purely virtual function analyze();
check if emitter has already connected or if self-emission
driver-side dependency check
Definition at line 90 of file secondarydriver.cpp.
References XDriver::abortRecordingNReadLock(), analyze(), checkDeepDependency(), checkDependency(), XDriver::finishRecordingNReadLock(), XNode::getLabel(), XNode::getName(), m_connections, XKameError::msg(), XKameError::print(), XDriver::tryStartRecording(), and visualize().
Referenced by requestAnalysis().
void XSecondaryDriver::beforeItemChanged (const shared_ptr< XValueNodeBase > & item) [private]
changes in items are not allowed while onRecord() is emitting
Definition at line 169 of file secondarydriver.cpp.
References m_connections, and XRWLock::writeLock().
Referenced by connect().
The documentation for this class was generated from the following files:
kame/driver/secondarydriver.h
kame/driver/secondarydriver.cpp