KAME2: XPulser Class Reference
XPulser Class Reference
#include <pulserdriver.h>
Detailed Description
Base class of NMR Pulsers.
Definition at line 33 of file pulserdriver.h.
Public Types
enum { N_COMB_MODE_OFF = 0, N_COMB_MODE_ON = 1, N_COMB_MODE_P1_ALT = 2, N_COMB_MODE_COMB_ALT = 3 }
driver specific part below
enum { N_RT_MODE_FIXREP = 0, N_RT_MODE_FIXREST = 1 }
enum { MAX_NUM_PHASE_CYCLE = 16 }
enum { NUM_DO_PORTS = 16 }
# of digital-pulse ports.
Public Member Functions
virtual void showForms ()
show all forms belonging to driver
const shared_ptr< XBoolNode > & output () const
const shared_ptr< XComboNode > & combMode () const
const shared_ptr< XComboNode > & rtMode () const
const shared_ptr< XComboNode > & numPhaseCycle () const
How many cycles in phase cycling.
const shared_ptr< XDoubleNode > & rtime () const
Repetition/Rest Time [ms].
const shared_ptr< XDoubleNode > & tau () const
[us]
const shared_ptr< XDoubleNode > & combPW () const
PulseWidths [us].
const shared_ptr< XDoubleNode > & pw1 () const
PulseWidths [us].
const shared_ptr< XDoubleNode > & pw2 () const
PulseWidths [us].
const shared_ptr< XDoubleNode > & combPT () const
Comb pulse periodic term [us].
const shared_ptr< XDoubleNode > & combP1 () const
P1 and P1 alternative.
const shared_ptr< XDoubleNode > & combP1Alt () const
P1 and P1 alternative.
const shared_ptr< XDoubleNode > & aswSetup () const
Analog switch setting, setup(proceeding) time before the first spin echo.
const shared_ptr< XDoubleNode > & aswHold () const
Analog switch setting, hold time after the last spin echo.
const shared_ptr< XDoubleNode > & altSep () const
Separation time in DSO record, cause a shift of trigger of DSO in alternatively mode.
const shared_ptr< XDoubleNode > & g2Setup () const
Setup time of pre-gating port and QPSK.
const shared_ptr< XUIntNode > & combNum () const
# of comb pulses
const shared_ptr< XUIntNode > & echoNum () const
# of Spin echoes (i.e. pi pulses)
const shared_ptr< XBoolNode > & drivenEquilibrium () const
polarize spins after pulse sequence or not
const shared_ptr< XDoubleNode > & combOffRes () const
off-resonance comb pulses
const shared_ptr< XComboNode > & combFunc () const
Pulse Modulation.
const shared_ptr< XComboNode > & p1Func () const
Pulse Modulation.
const shared_ptr< XComboNode > & p2Func () const
Pulse Modulation.
const shared_ptr< XDoubleNode > & combLevel () const
[dB], Pulse Modulation
const shared_ptr< XDoubleNode > & p1Level () const
[dB], Pulse Modulation
const shared_ptr< XDoubleNode > & p2Level () const
[dB], Pulse Modulation
const shared_ptr< XDoubleNode > & masterLevel () const
[dB]
const shared_ptr< XBoolNode > & induceEmission () const
const shared_ptr< XDoubleNode > & induceEmissionPhase () const
const shared_ptr< XDoubleNode > & qamOffset1 () const
const shared_ptr< XDoubleNode > & qamOffset2 () const
[F.S.]
const shared_ptr< XDoubleNode > & qamLevel1 () const
const shared_ptr< XDoubleNode > & qamLevel2 () const
< Quadrature Amplitude Modulation. Amplitude compensation factor.
const shared_ptr< XDoubleNode > & qamDelay1 () const
const shared_ptr< XDoubleNode > & qamDelay2 () const
< Delaying compensation [us].
const shared_ptr< XDoubleNode > & difFreq () const
[MHz]
const shared_ptr< XDoubleNode > & qswDelay () const
Q-switch setting, period after the end-edge of pulses [us].
const shared_ptr< XDoubleNode > & qswWidth () const
Q-switch setting, width of suppression [us].
const shared_ptr< XDoubleNode > & qswSoftSWOff () const
Q-switch setting, second pulse [us].
const shared_ptr< XBoolNode > & qswPiPulseOnly () const
Q-switch setting, use QSW only for pi pulses.
const shared_ptr< XBoolNode > & invertPhase () const
const shared_ptr< XBoolNode > & conserveStEPhase () const
const shared_ptr< XComboNode > & portSel (unsigned int port) const
int16_t combModeRecorded () const
ver 1 records.
double rtimeRecorded () const
double tauRecorded () const
double pw1Recorded () const
double pw2Recorded () const
double combP1Recorded () const
double altSepRecorded () const
double combP1AltRecorded () const
double aswSetupRecorded () const
double aswHoldRecorded () const
double difFreqRecorded () const
ver 2 records.
double combPWRecorded () const
double combPTRecorded () const
uint16_t echoNumRecorded () const
uint16_t combNumRecorded () const
int16_t rtModeRecorded () const
uint16_t numPhaseCycleRecorded () const
bool invertPhaseRecorded () const
ver 3 records [experimental].
double periodicTermRecorded () const
periodic term of one cycle [ms].
Protected Types
enum {
PORTSEL_UNSEL = -1, PORTSEL_GATE = 0, PORTSEL_PREGATE = 1, PORTSEL_GATE3 = 2,
PORTSEL_TRIG1 = 3, PORTSEL_TRIG2 = 4, PORTSEL_ASW = 5, PORTSEL_QSW = 6,
PORTSEL_PULSE1 = 7, PORTSEL_PULSE2 = 8, PORTSEL_COMB = 9, PORTSEL_COMB_FM = 10,
PORTSEL_QPSK_A = 11, PORTSEL_QPSK_B = 12, PORTSEL_QPSK_OLD_NONINV = 13, PORTSEL_QPSK_OLD_INV = 14,
PORTSEL_QPSK_OLD_PSGATE = 15
}
indice for return values of portSel().
enum {
PAT_DO_MASK = (1 << NUM_DO_PORTS) - 1, PAT_QAM_PHASE = (1 << NUM_DO_PORTS), PAT_QAM_PHASE_MASK = PAT_QAM_PHASE * 3, PAT_QAM_PULSE_IDX = PAT_QAM_PHASE * 4,
PAT_QAM_PULSE_IDX_P1 = PAT_QAM_PULSE_IDX * 1, PAT_QAM_PULSE_IDX_P2 = PAT_QAM_PULSE_IDX * 2, PAT_QAM_PULSE_IDX_PCOMB = PAT_QAM_PULSE_IDX * 3, PAT_QAM_PULSE_IDX_INDUCE_EMISSION = PAT_QAM_PULSE_IDX * 4,
PAT_QAM_PULSE_IDX_MASK = PAT_QAM_PULSE_IDX * 15, PAT_QAM_MASK = PAT_QAM_PHASE_MASK | PAT_QAM_PULSE_IDX_MASK
}
for RelPatList patterns.
typedef std::deque< RelPat > RelPatList
typedef RelPatList::iterator RelPatListIterator
typedef FFT::twindowfunc tpulsefunc
Protected Member Functions
XPulser (const char *name, bool runtime, const shared_ptr< XScalarEntryList > &scalarentries, const shared_ptr< XInterfaceList > &interfaces, const shared_ptr< XThermometerList > &thermometers, const shared_ptr< XDriverList > &drivers)
unsigned int selectedPorts (int func) const
virtual void start ()
Start up your threads, connect GUI, and activate signals.
virtual void stop ()
virtual void analyzeRaw () throw (XRecordError&)
virtual void visualize ()
void writeRaw ()
tpulsefunc pulseFunc (const XString &str) const
virtual void changeOutput (bool output, unsigned int blankpattern)=0
send patterns to pulser or turn-off
virtual void createNativePatterns ()=0
convert RelPatList to native patterns
virtual double resolution () const =0
time resolution [ms]
virtual double resolutionQAM () const =0
virtual double minPulseWidth () const =0
minimum period of pulses [ms]
virtual bool haveQAMPorts () const =0
existense of AO ports.
const std::vector
< std::complex< double > > & qamWaveForm (unsigned int idx) const
Protected Attributes
int16_t m_combModeRecorded
ver 1 records
double m_rtimeRecorded
double m_tauRecorded
double m_pw1Recorded
double m_pw2Recorded
double m_combP1Recorded
double m_altSepRecorded
double m_combP1AltRecorded
double m_aswSetupRecorded
double m_aswHoldRecorded
double m_difFreqRecorded
ver 2 records
double m_combPWRecorded
double m_combPTRecorded
uint16_t m_echoNumRecorded
uint16_t m_combNumRecorded
int16_t m_rtModeRecorded
uint16_t m_numPhaseCycleRecorded
bool m_invertPhaseRecorded
ver 3 records
RelPatList m_relPatList
Private Member Functions
void onMoreConfigShow (const shared_ptr< XNode > &)
void onPulseChanged (const shared_ptr< XValueNodeBase > &)
void rawToRelPat () throw (XRecordError&)
create RelPatList
void makeWaveForm (unsigned int pnum_minus_1, double pw, unsigned int to_center, tpulsefunc func, double dB, double freq=0.0, double phase=0.0)
prepare waveforms for QAM.
double rintTermMilliSec (double msec) const
truncate time by resolution().
double rintTermMicroSec (double usec) const
uint64_t ceilSampsMicroSec (double us) const
uint64_t rintSampsMicroSec (double us) const
uint64_t rintSampsMilliSec (double ms) const
Private Attributes
const shared_ptr< XBoolNode > m_output
const shared_ptr< XComboNode > m_combMode
const shared_ptr< XComboNode > m_rtMode
const shared_ptr< XDoubleNode > m_rt
Repetition/Rest Time [ms].
const shared_ptr< XDoubleNode > m_tau
[us]
const shared_ptr< XDoubleNode > m_combPW
const shared_ptr< XDoubleNode > m_pw1
const shared_ptr< XDoubleNode > m_pw2
PulseWidths [us].
const shared_ptr< XUIntNode > m_combNum
# of comb pulses
const shared_ptr< XDoubleNode > m_combPT
Comb pulse periodic term [us].
const shared_ptr< XDoubleNode > m_combP1
const shared_ptr< XDoubleNode > m_combP1Alt
P1 and P1 alternative.
const shared_ptr< XDoubleNode > m_aswSetup
Analog switch setting, setup(proceeding) time before the first spin echo.
const shared_ptr< XDoubleNode > m_aswHold
Analog switch setting, hold time after the last spin echo.
const shared_ptr< XDoubleNode > m_altSep
Separation time in DSO record, cause a shift of trigger of DSO in alternatively mode.
const shared_ptr< XDoubleNode > m_g2Setup
Setup time of pre-gating port and QPSK.
const shared_ptr< XUIntNode > m_echoNum
# of Spin echoes (i.e. pi pulses)
const shared_ptr< XDoubleNode > m_combOffRes
off-resonance comb pulses
const shared_ptr< XBoolNode > m_drivenEquilibrium
polarize spins after pulse sequence or not
const shared_ptr< XComboNode > m_numPhaseCycle
How many cycles in phase cycling.
const shared_ptr< XComboNode > m_p1Func
const shared_ptr< XComboNode > m_p2Func
const shared_ptr< XComboNode > m_combFunc
Pulse Modulation.
const shared_ptr< XDoubleNode > m_p1Level
const shared_ptr< XDoubleNode > m_p2Level
const shared_ptr< XDoubleNode > m_combLevel
[dB], Pulse Modulation
const shared_ptr< XDoubleNode > m_masterLevel
[dB]
const shared_ptr< XDoubleNode > m_qamOffset1
const shared_ptr< XDoubleNode > m_qamOffset2
[F.S.]
const shared_ptr< XDoubleNode > m_qamLevel1
const shared_ptr< XDoubleNode > m_qamLevel2
const shared_ptr< XDoubleNode > m_qamDelay1
const shared_ptr< XDoubleNode > m_qamDelay2
[us]
const shared_ptr< XDoubleNode > m_difFreq
[MHz]
const shared_ptr< XBoolNode > m_induceEmission
const shared_ptr< XDoubleNode > m_induceEmissionPhase
const shared_ptr< XDoubleNode > m_qswDelay
const shared_ptr< XDoubleNode > m_qswWidth
const shared_ptr< XDoubleNode > m_qswSoftSWOff
const shared_ptr< XBoolNode > m_invertPhase
const shared_ptr< XBoolNode > m_conserveStEPhase
const shared_ptr< XBoolNode > m_qswPiPulseOnly
shared_ptr< XComboNode > m_portSel [NUM_DO_PORTS]
const shared_ptr< XNode > m_moreConfigShow
xqcon_ptr m_conOutput
xqcon_ptr m_conCombMode
xqcon_ptr m_conRTMode
xqcon_ptr m_conRT
xqcon_ptr m_conTau
xqcon_ptr m_conCombPW
xqcon_ptr m_conPW1
xqcon_ptr m_conPW2
xqcon_ptr m_conCombNum
xqcon_ptr m_conCombPT
xqcon_ptr m_conCombP1
xqcon_ptr m_conCombP1Alt
xqcon_ptr m_conASWHold
xqcon_ptr m_conASWSetup
xqcon_ptr m_conALTSep
xqcon_ptr m_conG2Setup
xqcon_ptr m_conEchoNum
xqcon_ptr m_conDrivenEquilibrium
xqcon_ptr m_conNumPhaseCycle
xqcon_ptr m_conCombOffRes
xqcon_ptr m_conInvertPhase
xqcon_ptr m_conConserveStEPhase
xqcon_ptr m_conCombFunc
xqcon_ptr m_conP1Func
xqcon_ptr m_conP2Func
xqcon_ptr m_conCombLevel
xqcon_ptr m_conP1Level
xqcon_ptr m_conP2Level
xqcon_ptr m_conMasterLevel
xqcon_ptr m_conQAMOffset1
xqcon_ptr m_conQAMOffset2
xqcon_ptr m_conQAMLevel1
xqcon_ptr m_conQAMLevel2
xqcon_ptr m_conQAMDelay1
xqcon_ptr m_conQAMDelay2
xqcon_ptr m_conMoreConfigShow
xqcon_ptr m_conDIFFreq
xqcon_ptr m_conInduceEmission
xqcon_ptr m_conInduceEmissionPhase
xqcon_ptr m_conQSWDelay
xqcon_ptr m_conQSWWidth
xqcon_ptr m_conQSWSoftSWOff
xqcon_ptr m_conQSWPiPulseOnly
xqcon_ptr m_conPortSel [NUM_DO_PORTS]
shared_ptr< XListener > m_lsnOnPulseChanged
shared_ptr< XListener > m_lsnOnMoreConfigShow
const qshared_ptr< FrmPulser > m_form
const qshared_ptr< FrmPulserMore > m_formMore
xqcon_ptr m_conPulserDriver
std::vector< std::complex
< double > > m_qamWaveForm [PAT_QAM_PULSE_IDX_MASK/PAT_QAM_PULSE_IDX]
Friends
class XQPulserDriverConnector
Classes
struct RelPat
Member Enumeration Documentation
anonymous enum
driver specific part below
See also:
combMode(), combModeRecorded().
Definition at line 51 of file pulserdriver.h.
anonymous enum
See also:
rtMode(), rtModeRecorded().
Definition at line 53 of file pulserdriver.h.
anonymous enum
See also:
numPhaseCycle(), numPhaseCycleRecorded().
Definition at line 55 of file pulserdriver.h.
anonymous enum [protected]
for RelPatList patterns.
See also:
RelPatList.
Definition at line 147 of file pulserdriver.h.
Member Function Documentation
void XPulser::showForms () [virtual]
show all forms belonging to driver
impliment form->show() here
Implements XDriver.
Definition at line 339 of file pulserdriver.cpp.
const shared_ptr<XComboNode>& XPulser::combMode () const [inline]
see above definitions in header file
Definition at line 60 of file pulserdriver.h.
References m_combMode.
Referenced by onPulseChanged(), start(), and stop().
const shared_ptr<XComboNode>& XPulser::rtMode () const [inline]
Control period to next pulse sequence Fix Repetition Time or Fix Rest Time which means time between pulse sequences
Definition at line 63 of file pulserdriver.h.
References m_rtMode.
Referenced by analyzeRaw(), onPulseChanged(), start(), and stop().
const shared_ptr<XDoubleNode>& XPulser::qamDelay2 () const [inline]
< Delaying compensation [us].
[us]
Definition at line 95 of file pulserdriver.h.
References m_qamDelay2.
Referenced by makeWaveForm(), start(), and stop().
unsigned int XPulser::selectedPorts (int func) const [protected]
func e.g. PORTSEL_GATE.
Returns:
bit mask.
Definition at line 672 of file pulserdriver.cpp.
Referenced by onPulseChanged(), and rawToRelPat().
void XPulser::stop () [protected, virtual]
Shut down your threads, unconnect GUI, and deactivate signals this may be called even if driver has already stopped.
Definition at line 454 of file pulserdriver.cpp.
References altSep(), aswHold(), aswSetup(), combFunc(), combLevel(), combMode(), combNum(), combOffRes(), combP1(), combP1Alt(), combPT(), combPW(), difFreq(), drivenEquilibrium(), echoNum(), g2Setup(), masterLevel(), numPhaseCycle(), p1Func(), p1Level(), p2Func(), p2Level(), pw1(), pw2(), qamDelay2(), qamLevel2(), qamOffset2(), qswDelay(), qswPiPulseOnly(), qswSoftSWOff(), qswWidth(), rtime(), rtMode(), and tau().
void XPulser::analyzeRaw () throw (XRecordError&) [protected, virtual]
this is called when raw is written unless dependency is broken convert raw to record
ver 2 records
ver 3 records
Definition at line 511 of file pulserdriver.cpp.
References combNum(), combPT(), combPW(), difFreq(), echoNum(), m_combModeRecorded, m_difFreqRecorded, m_invertPhaseRecorded, numPhaseCycle(), rawToRelPat(), and rtMode().
void XPulser::visualize () [protected, virtual]
this is called after analyze() or analyzeRaw() record is readLocked
impliment extra codes which do not need write-lock of record record is read-locked
Implements XDriver.
Definition at line 556 of file pulserdriver.cpp.
void XPulser::writeRaw () [protected]
push parameters. use this after clearRaw()
void XPulser::onPulseChanged (const shared_ptr< XValueNodeBase > & node) [private]
ver 1 records below
ver 2 records below
ver 3 records below
Definition at line 563 of file pulserdriver.cpp.
References altSep(), aswHold(), aswSetup(), changeOutput(), combMode(), combNum(), combP1(), combP1Alt(), combPT(), combPW(), createNativePatterns(), difFreq(), echoNum(), XNode::getLabel(), numPhaseCycle(), XKameError::print(), pw1(), pw2(), rintTermMilliSec(), rtime(), rtMode(), selectedPorts(), and tau().
Referenced by start().
Member Data Documentation
const shared_ptr<XComboNode> XPulser::m_combMode [private]
see above definitions in header file
Definition at line 234 of file pulserdriver.h.
Referenced by combMode().
const shared_ptr<XComboNode> XPulser::m_rtMode [private]
Control period to next pulse sequence Fix Repetition Time or Fix Rest Time which means time between pulse sequences
Definition at line 237 of file pulserdriver.h.
Referenced by rtMode().
The documentation for this class was generated from the following files:
modules/nmr/pulsercore/pulserdriver.h
modules/nmr/pulsercore/pulserdriver.cpp