/***************************************************************************
        Copyright (C) 2002-2023 Kentaro Kitagawa
                           kitag@issp.u-tokyo.ac.jp

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public
        License as published by the Free Software Foundation; either
        version 2 of the License, or (at your option) any later version.

        You should have received a copy of the GNU General
        Public License and a list of authors along with this program;
        see the files COPYING and AUTHORS.
***************************************************************************/
//---------------------------------------------------------------------------

#ifndef USERARBFUNCH
#define USERARBFUNCH

#include "arbfunc.h"
#include "chardevicedriver.h"
#include "charinterface.h"


class XArbFuncGenSCPI : public XCharDeviceDriver<XArbFuncGen> {
public:
    XArbFuncGenSCPI(const char *name, bool runtime,
        Transaction &tr_meas, const shared_ptr<XMeasure> &meas);
    virtual ~XArbFuncGenSCPI() {}

protected:
    virtual void changeOutput(bool active) override;
    virtual void changePulseCond() override;
    virtual void sendSoftwareTrigger() override;

    //! Be called just after opening interface. Call start() inside this routine appropriately.
    virtual void open() override;
private:

};

//! Agilent/Keysight 33250A 80 MHz function / arbitrary waveform generator.
//! It shares the Agilent 33xxx SCPI command set with the 3390, so it reuses
//! XArbFuncGenSCPI unchanged. The base constructor already configures GPIB
//! (EOS, serial-poll, wait times), so this works over NI USB-GPIB as well as LXI/TCP.
class XAgilent33250A : public XArbFuncGenSCPI {
public:
    XAgilent33250A(const char *name, bool runtime,
        Transaction &tr_meas, const shared_ptr<XMeasure> &meas);
    virtual ~XAgilent33250A() {}
protected:
    //! The 33250A lacks some 33220A/3390 commands (FUNC:PULSe:DCYCle, FUNC:PULSe:WIDTh,
    //! stand-alone PHASe). Send only commands valid on the 33250A so it does not queue
    //! SCPI errors ("Error generated by remote interface" on the front panel).
    virtual void changePulseCond() override;
    //! The base open() queries FUNC:PULSe:DCYCle? for non-square functions, which the 33250A
    //! does not implement; the query then times out and the connection fails. Read back the
    //! state using only 33250A-valid queries.
    virtual void open() override;
};

#endif
