KAME2: XNMRT1 Class Reference
XNMRT1 Class Reference
#include <nmrrelax.h>
Detailed Description
Measure Relaxation Curve.
Definition at line 38 of file nmrrelax.h.
Public Types
enum MEASMODE { MEAS_T1 = 0, MEAS_T2 = 1, MEAS_ST_E = 2 }
Public Member Functions
virtual void showForms ()
show all forms belonging to driver
const shared_ptr< XScalarEntry > & t1inv () const
Holds 1/T1 or 1/T2 and its std. deviation.
const shared_ptr< XScalarEntry > & t1invErr () const
const shared_ptr< XItemNode
< XDriverList, XPulser > > & pulser () const
const shared_ptr< XItemNode
< XDriverList,
XNMRPulseAnalyzer > > & pulse1 () const
const shared_ptr< XItemNode
< XDriverList,
XNMRPulseAnalyzer > > & pulse2 () const
const shared_ptr< XBoolNode > & active () const
If active, a control to Pulser is allowed.
const shared_ptr< XBoolNode > & autoPhase () const
Deduce phase from data.
const shared_ptr< XBoolNode > & mInftyFit () const
Fit 3 parameters.
const shared_ptr< XBoolNode > & absFit () const
Use absolute value, ignoring phase.
const shared_ptr< XDoubleNode > & p1Min () const
Region of P1 or 2tau for fitting, display, control of pulser [ms].
const shared_ptr< XDoubleNode > & p1Max () const
const shared_ptr< XDoubleNode > & phase () const
(Deduced) phase of echoes [deg.]
const shared_ptr< XDoubleNode > & freq () const
Center freq of echoes [kHz].
const shared_ptr< XComboNode > & windowFunc () const
FFT Window Function.
const shared_ptr< XComboNode > & windowWidth () const
FFT Window Length.
const shared_ptr< XBoolNode > & autoWindow () const
Auto-select window.
const shared_ptr< XComboNode > & mode () const
T1/T2/StE measurement.
const shared_ptr< XUIntNode > & smoothSamples () const
# of Samples for fitting and display
const shared_ptr< XComboNode > & p1Dist () const
Distribution of P1 or 2tau.
const shared_ptr< XItemNode
< XRelaxFuncList, XRelaxFunc > > & relaxFunc () const
Relaxation Function.
Protected Member Functions
XNMRT1 (const char *name, bool runtime, const shared_ptr< XScalarEntryList > &scalarentries, const shared_ptr< XInterfaceList > &interfaces, const shared_ptr< XThermometerList > &thermometers, const shared_ptr< XDriverList > &drivers)
virtual void analyze (const shared_ptr< XDriver > &emitter) throw (XRecordError&)
virtual void visualize ()
virtual bool checkDependency (const shared_ptr< XDriver > &emitter) const
Private Member Functions
void onClearAll (const shared_ptr< XNode > &)
void onResetFit (const shared_ptr< XNode > &)
void onActiveChanged (const shared_ptr< XValueNodeBase > &)
void onCondChanged (const shared_ptr< XValueNodeBase > &)
void analyzeSpectrum (const shared_ptr< XNMRPulseAnalyzer > &pulse, std::deque< std::complex< double > > &value_by_cond)
void analyzeSpectrum (const std::vector< std::complex< double > > &wave, int origin, double cf, std::deque< std::complex< double > > &value_by_cond)
XString iterate (shared_ptr< XRelaxFunc > &relax, int itercnt)
Private Attributes
shared_ptr< XRelaxFuncList > m_relaxFuncs
List of relaxation functions.
const shared_ptr< XScalarEntry > m_t1inv
Holds 1/T1 or 1/T2 and its std. deviation.
const shared_ptr< XScalarEntry > m_t1invErr
const shared_ptr< XItemNode
< XDriverList, XPulser > > m_pulser
const shared_ptr< XItemNode
< XDriverList,
XNMRPulseAnalyzer > > m_pulse1
const shared_ptr< XItemNode
< XDriverList,
XNMRPulseAnalyzer > > m_pulse2
const shared_ptr< XBoolNode > m_active
const shared_ptr< XBoolNode > m_autoPhase
const shared_ptr< XBoolNode > m_mInftyFit
const shared_ptr< XBoolNode > m_absFit
const shared_ptr< XDoubleNode > m_p1Min
const shared_ptr< XDoubleNode > m_p1Max
const shared_ptr< XDoubleNode > m_phase
const shared_ptr< XDoubleNode > m_freq
const shared_ptr< XDoubleNode > m_bandWidth
const shared_ptr< XComboNode > m_windowFunc
const shared_ptr< XComboNode > m_windowWidth
const shared_ptr< XBoolNode > m_autoWindow
const shared_ptr< XComboNode > m_mode
const shared_ptr< XUIntNode > m_smoothSamples
const shared_ptr< XComboNode > m_p1Dist
const shared_ptr< XItemNode
< XRelaxFuncList, XRelaxFunc > > m_relaxFunc
const shared_ptr< XNode > m_resetFit
const shared_ptr< XNode > m_clearAll
const shared_ptr< XStringNode > m_fitStatus
shared_ptr< XListener > m_lsnOnClearAll
shared_ptr< XListener > m_lsnOnResetFit
shared_ptr< XListener > m_lsnOnActiveChanged
shared_ptr< XListener > m_lsnOnCondChanged
xqcon_ptr m_conP1Min
xqcon_ptr m_conP1Max
xqcon_ptr m_conPhase
xqcon_ptr m_conFreq
xqcon_ptr m_conWindowFunc
xqcon_ptr m_conWindowWidth
xqcon_ptr m_conAutoWindow
xqcon_ptr m_conSmoothSamples
xqcon_ptr m_conASWClearance
xqcon_ptr m_conFitStatus
xqcon_ptr m_conP1Dist
xqcon_ptr m_conRelaxFunc
xqcon_ptr m_conClearAll
xqcon_ptr m_conResetFit
xqcon_ptr m_conActive
xqcon_ptr m_conAutoPhase
xqcon_ptr m_conMInftyFit
xqcon_ptr m_conAbsFit
xqcon_ptr m_conMode
xqcon_ptr m_conPulser
xqcon_ptr m_conPulse1
xqcon_ptr m_conPulse2
std::deque< double > m_windowWidthList
std::deque< shared_ptr
< ConvolutionCache > > m_convolutionCache
shared_ptr< SpectrumSolverWrapper > m_solver
std::deque< RawPt > m_pts
Store all measured points.
std::deque< Pt > m_sumpts
Store reduced points to manage fitting and display.
const qshared_ptr< FrmNMRT1 > m_form
const shared_ptr< XStatusPrinter > m_statusPrinter
const shared_ptr< XWaveNGraph > m_wave
double m_params [3]
fitting parameters; 1/T1, c, a; ex. f(t) = c*exp(-t/T1) + a
double m_errors [3]
std. deviations
XTime m_timeClearRequested
Friends
class XRelaxFunc
class XRelaxFuncPlot
Classes
struct ConvolutionCache
struct NLLS
for Non-Lenear-Least-Square fitting
struct Pt
For fitting and display.
struct RawPt
Raw measured points.
Member Function Documentation
void XNMRT1::analyze (const shared_ptr< XDriver > & emitter) throw (XRecordError&) [protected, virtual]
this is called when connected driver emit a signal unless dependency is broken all connected drivers are readLocked
Implements XSecondaryDriver.
Definition at line 350 of file nmrrelax.cpp.
References absFit(), active(), autoPhase(), autoWindow(), XNMRT1::Pt::c, freq(), XNMRT1::Pt::isigma, iterate(), m_errors, m_params, m_pts, m_sumpts, m_wave, mode(), XNMRT1::Pt::p1, p1Min(), phase(), relaxFunc(), smoothSamples(), t1inv(), XSecondaryDriver::unlockConnection(), XNMRT1::Pt::value_by_cond, windowFunc(), and windowWidth().
void XNMRT1::visualize () [protected, virtual]
this is called after analyze() or analyzeRaw() record is readLocked
Implements XSecondaryDriver.
Definition at line 600 of file nmrrelax.cpp.
References m_sumpts, m_wave, mode(), and XDriver::time().
bool XNMRT1::checkDependency (const shared_ptr< XDriver > & emitter) const [protected, virtual]
check connected drivers have valid time
Returns:
true if dependency is resolved
Implements XSecondaryDriver.
Definition at line 322 of file nmrrelax.cpp.
XString XNMRT1::iterate (shared_ptr< XRelaxFunc > & relax, int itercnt) [private]
Do fitting iterations itercnt times
Parameters:
relax a pointer to a realaxation function
itercnt counts
buf a message will be passed
Definition at line 374 of file nmrrelaxfit.cpp.
References XNMRT1::NLLS::fixed_minfty, XNMRT1::NLLS::is_minftyfit, m_errors, m_params, m_sumpts, mInftyFit(), mode(), and p1Min().
Referenced by analyze().
Member Data Documentation
const shared_ptr<XWaveNGraph> XNMRT1::m_wave [private]
Store reduced points
See also:
m_pt, m_sumpts
Definition at line 205 of file nmrrelax.h.
Referenced by analyze(), and visualize().
The documentation for this class was generated from the following files:
modules/nmr/nmrrelax.h
modules/nmr/nmrrelax.cpp
modules/nmr/nmrrelaxfit.cpp