KAME2: XDriver Class Reference
XDriver Class Reference
#include <driver.h>
Detailed Description
Base class for all instrument drivers.
Definition at line 29 of file driver.h.
Public Member Functions
virtual void showForms ()=0
show all forms belonging to driver
XTalker< shared_ptr< XDriver > > & onRecord ()
called during parsing
void readLockRecord () const
lock analysed members and entries
void readUnlockRecord () const
const XTime & time () const
const XTime & timeAwared () const
virtual const shared_ptr
< XRecordDependency > dependency () const =0
Protected Member Functions
XDriver (const char *name, bool runtime, const shared_ptr< XScalarEntryList > &scalarentries, const shared_ptr< XInterfaceList > &interfaces, const shared_ptr< XThermometerList > &thermometers, const shared_ptr< XDriverList > &drivers)
virtual void visualize ()=0
bool tryStartRecording ()
void finishRecordingNReadLock (const XTime &time_awared, const XTime &time_recorded)
void abortRecording ()
leave existing record.
void abortRecordingNReadLock ()
leave existing record.
Private Attributes
XTalker< shared_ptr< XDriver > > m_tlkRecord
Lock this record and dependent drivers.
XRecursiveRWLock m_recordLock
mutex for record
XTime m_recordTime
XTime m_awaredTime
Classes
struct XBufferUnderflowRecordError
size of raw record is not enough to continue analyzing
struct XRecordError
struct XSkippedRecordError
throwing this exception will skip signal emission, assuming record is kept valid.
Member Function Documentation
const XTime& XDriver::time () const [inline]
recorded time. time when phenomenon finished and recorded. analyses must be based on this time. zero if record is invalid.
Definition at line 54 of file driver.h.
References m_recordTime.
Referenced by XNMRT1::visualize().
const XTime& XDriver::timeAwared () const [inline]
time when an operator (you) can see a phenomenon. manual operations (ex. pushing clear button) must be based on this time. time when a phenomenon starts if measuement is on real-time. time when record is read if measuement is *not* on real-time. unknown if record is invalid.
Definition at line 60 of file driver.h.
References m_awaredTime.
virtual void XDriver::visualize () [protected, pure virtual]
this is called after analyze() or analyzeRaw() record is readLocked This might be called even if the record is broken (time() == false).
Implemented in XSecondaryDriver, XDSO, XNetworkAnalyzer, XNMRT1, and XPulser.
bool XDriver::tryStartRecording () [protected]
writeLock record and readLock all dependent drivers
Returns:
true if locked.
Definition at line 61 of file driver.cpp.
References m_recordLock, and XRecursiveRWLock::tryWriteLock().
Referenced by XSecondaryDriver::onConnectedRecorded().
void XDriver::finishRecordingNReadLock (const XTime & time_awared, const XTime & time_recorded) [protected]
m_tlkRecord is invoked after unlocking
See also:
time(), timeAwared()
Definition at line 65 of file driver.cpp.
References m_awaredTime, m_recordLock, m_recordTime, onRecord(), XTalker< tArg >::talk(), and XRecursiveRWLock::writeUnlockNReadLock().
Referenced by XSecondaryDriver::onConnectedRecorded().
Member Data Documentation
XTime XDriver::m_recordTime [private]
See also:
time()
Definition at line 100 of file driver.h.
Referenced by finishRecordingNReadLock(), and time().
XTime XDriver::m_awaredTime [private]
See also:
timeAwared()
Definition at line 102 of file driver.h.
Referenced by finishRecordingNReadLock(), and timeAwared().
The documentation for this class was generated from the following files:
kame/driver/driver.h
kame/driver/driver.cpp