KAME2: XNetworkAnalyzer Class Reference
XNetworkAnalyzer Class Reference
#include <networkanalyzer.h>
Detailed Description
Base class for digital storage oscilloscope.
Definition at line 29 of file networkanalyzer.h.
Public Member Functions
virtual ~XNetworkAnalyzer ()
usually nothing to do.
virtual void showForms ()
show all forms belonging to driver.
Protected Member Functions
XNetworkAnalyzer (const char *name, bool runtime, const shared_ptr< XScalarEntryList > &scalarentries, const shared_ptr< XInterfaceList > &interfaces, const shared_ptr< XThermometerList > &thermometers, const shared_ptr< XDriverList > &drivers)
virtual void start ()
Start up your threads, connect GUI, and activate signals.
virtual void stop ()
virtual void analyzeRaw () throw (XRecordError&)
virtual void visualize ()
const shared_ptr< XScalarEntry > & marker1X () const
driver specific part below
const shared_ptr< XScalarEntry > & marker1Y () const
const shared_ptr< XScalarEntry > & marker2X () const
const shared_ptr< XScalarEntry > & marker2Y () const
const shared_ptr< XDoubleNode > & startFreq () const
const shared_ptr< XDoubleNode > & stopFreq () const
const shared_ptr< XComboNode > & points () const
const shared_ptr< XUIntNode > & average () const
double startFreqRecorded () const
Records below.
double freqIntervalRecorded () const
[MHz]
unsigned int lengthRecorded () const
[MHz]
const double * traceRecorded () const
virtual void onStartFreqChanged (const shared_ptr< XValueNodeBase > &)=0
virtual void onStopFreqChanged (const shared_ptr< XValueNodeBase > &)=0
virtual void onAverageChanged (const shared_ptr< XValueNodeBase > &)=0
virtual void onPointsChanged (const shared_ptr< XValueNodeBase > &)=0
virtual void getMarkerPos (unsigned int num, double &x, double &y)=0
virtual void oneSweep ()=0
virtual void startContSweep ()=0
virtual void acquireTrace (unsigned int ch)=0
virtual void convertRaw ()=0 throw (XRecordError&)
convert raw to dispaly-able
Protected Attributes
std::vector< double > m_traceRecorded
double m_startFreqRecorded
double m_freqIntervalRecorded
std::deque< std::pair< double,
double > > m_markersRecorded
Private Member Functions
const shared_ptr< XWaveNGraph > & waveForm () const
void * execute (const atomic< bool > &)
Private Attributes
const shared_ptr< XScalarEntry > m_marker1X
const shared_ptr< XScalarEntry > m_marker1Y
const shared_ptr< XScalarEntry > m_marker2X
const shared_ptr< XScalarEntry > m_marker2Y
const shared_ptr< XDoubleNode > m_startFreq
const shared_ptr< XDoubleNode > m_stopFreq
const shared_ptr< XComboNode > m_points
const shared_ptr< XUIntNode > m_average
const qshared_ptr
< FrmNetworkAnalyzer > m_form
const shared_ptr< XWaveNGraph > m_waveForm
shared_ptr< XListener > m_lsnOnStartFreqChanged
shared_ptr< XListener > m_lsnOnStopFreqChanged
shared_ptr< XListener > m_lsnOnPointsChanged
shared_ptr< XListener > m_lsnOnAverageChanged
xqcon_ptr m_conStartFreq
xqcon_ptr m_conStopFreq
xqcon_ptr m_conPoints
xqcon_ptr m_conAverage
shared_ptr< XGraph > m_graph
shared_ptr< XXYPlot > m_markerPlot
shared_ptr< XThread
< XNetworkAnalyzer > > m_thread
Member Function Documentation
void XNetworkAnalyzer::showForms () [virtual]
show all forms belonging to driver.
impliment form->show() here
Implements XDriver.
Definition at line 96 of file networkanalyzer.cpp.
void XNetworkAnalyzer::stop () [protected, virtual]
Shut down your threads, unconnect GUI, and deactivate signals this may be called even if driver has already stopped.
Definition at line 114 of file networkanalyzer.cpp.
void XNetworkAnalyzer::analyzeRaw () throw (XRecordError&) [protected, virtual]
this is called when raw is written unless dependency is broken convert raw to record
Definition at line 127 of file networkanalyzer.cpp.
References convertRaw().
void XNetworkAnalyzer::visualize () [protected, virtual]
this is called after analyze() or analyzeRaw() record is readLocked
Implements XDriver.
Definition at line 149 of file networkanalyzer.cpp.
References freqIntervalRecorded(), lengthRecorded(), and startFreqRecorded().
The documentation for this class was generated from the following files:
modules/networkanalyzer/networkanalyzer.h
modules/networkanalyzer/networkanalyzer.cpp