KAME2: atomic_shared_ptr< T > Class Template Reference
atomic_shared_ptr< T > Class Template Reference
#include <atomic_smart_ptr.h>
Detailed Description
template<typename T>
class atomic_shared_ptr< T >
This is an atomic variant of boost::shared_ptr<>.
atomic_shared_ptr<> can be shared among threads by the use of operator=(_target_), swap(_target_). An instance of atomic_shared_ptr<T> holds:
a) a pointer to _atomic_shared_ptr_gref<T>, which is a struct consisting of a pointer to the T-type object, and a global reference counter.
b) a local (temporary) reference counter, which is embedded in the above pointer by using the least significant bits that should be usually zero.
The values of a) and b), m_ref, are atomically handled with CAS machine codes. The purpose of b) the local reference counter is to tell the "observation" to the shared target before increasing the global reference counter. This process is implemented in _reserve_scan_().
A function _leave_scan_() tries to decrease the local counter first. When it fails, the global counter is decreased.
To swap the pointer and local reference counter (which will be reset to zero), the setter must adds the local counting to the global counter before swapping.
See also:
atomic_scoped_ptr
Definition at line 99 of file atomic_smart_ptr.h.
Public Types
typedef
_atomic_shared_ptr_gref< T > Ref
typedef uintptr_t Refcnt
Public Member Functions
template<typename Y>
atomic_shared_ptr (Y *y)
atomic_shared_ptr (const atomic_shared_ptr &t)
template<typename Y>
atomic_shared_ptr (const atomic_shared_ptr< Y > &y)
atomic_shared_ptr & operator= (const atomic_shared_ptr &t)
template<typename Y>
atomic_shared_ptr & operator= (const atomic_shared_ptr< Y > &y)
void reset ()
This instance is atomically reset to null pointer.
template<typename Y>
void reset (Y *y)
void swap (atomic_shared_ptr &x)
bool compareAndSwap (const atomic_shared_ptr &oldvalue, atomic_shared_ptr &target)
T * get () const
The return value is apparently not valid for a shared instance.
T & operator* () const
The return value is apparently not valid for a shared instance.
T * operator-> () const
The return value is apparently not valid for a shared instance.
bool operator! () const
The return value is apparently not valid for a shared instance.
operator bool () const
The return value is apparently not valid for a shared instance.
Ref * _scan_ () const
Ref * _reserve_scan_ (Refcnt *) const
void _leave_scan_ (Ref *) const
Private Types
typedef uintptr_t _RefLocal
Private Member Functions
Ref * _pref () const
A pointer to global reference struct.
Refcnt _refcnt () const
Private Attributes
_RefLocal m_ref
Member Function Documentation
template<typename T> atomic_shared_ptr& atomic_shared_ptr< T >::operator= (const atomic_shared_ptr< T > & t) [inline]
Parameters:
t This instance is atomically replaced with t.
Definition at line 126 of file atomic_smart_ptr.h.
template<typename T> template<typename Y> atomic_shared_ptr& atomic_shared_ptr< T >::operator= (const atomic_shared_ptr< Y > & y) [inline]
Parameters:
y This instance is atomically replaced with t.
Definition at line 131 of file atomic_smart_ptr.h.
template<typename T> template<typename Y> void atomic_shared_ptr< T >::reset (Y * y) [inline]
Parameters:
y This instance is atomically reset with a pointer y.
Definition at line 140 of file atomic_smart_ptr.h.
template<typename T> void atomic_shared_ptr< T >::swap (atomic_shared_ptr< T > & x) [inline]
Parameters:
x x is atomically swapped with this instance. Nevertheless, this instance is not atomically replaced. That is, "this" must not be shared among threads.
Definition at line 278 of file atomic_smart_ptr.h.
References atomic_shared_ptr< T >::_leave_scan_(), atomic_shared_ptr< T >::_pref(), atomic_shared_ptr< T >::_refcnt(), atomic_shared_ptr< T >::_reserve_scan_(), atomic_shared_ptr< T >::m_ref, and _atomic_shared_ptr_gref< T >::refcnt.
Referenced by atomic_shared_ptr< std::deque< XString > >::operator=().
template<typename T> bool atomic_shared_ptr< T >::compareAndSwap (const atomic_shared_ptr< T > & oldvalue, atomic_shared_ptr< T > & target) [inline]
Returns:
true if succeeded.
See also:
swap()
Definition at line 305 of file atomic_smart_ptr.h.
References atomic_shared_ptr< T >::_leave_scan_(), atomic_shared_ptr< T >::_pref(), atomic_shared_ptr< T >::_refcnt(), atomic_shared_ptr< T >::_reserve_scan_(), atomic_shared_ptr< T >::m_ref, and _atomic_shared_ptr_gref< T >::refcnt.
template<typename T> atomic_shared_ptr< T >::Ref * atomic_shared_ptr< T >::_scan_ () const [inline]
atomically scans m_ref and increases the global reference counter. _scan_ is used for atomically coping the pointer.
Definition at line 240 of file atomic_smart_ptr.h.
References atomic_shared_ptr< T >::_leave_scan_(), atomic_shared_ptr< T >::_reserve_scan_(), and _atomic_shared_ptr_gref< T >::refcnt.
template<typename T> atomic_shared_ptr< T >::Ref * atomic_shared_ptr< T >::_reserve_scan_ (Refcnt * rcnt) const [inline]
atomically scans m_ref and increases the local (temporary) reference counter. use _leave_scan_ to release the temporary reference.
Definition at line 203 of file atomic_smart_ptr.h.
References atomic_shared_ptr< T >::_pref(), and atomic_shared_ptr< T >::_refcnt().
Referenced by atomic_shared_ptr< T >::_scan_(), atomic_shared_ptr< T >::compareAndSwap(), and atomic_shared_ptr< T >::swap().
template<typename T> void atomic_shared_ptr< T >::_leave_scan_ (Ref * pref) const [inline]
tries to decrease local (temporary) reference counter. In case the reference is lost, _leave_scan_ releases the global reference counter instead.
Definition at line 252 of file atomic_smart_ptr.h.
References atomic_shared_ptr< T >::_pref(), atomic_shared_ptr< T >::_refcnt(), and _atomic_shared_ptr_gref< T >::refcnt.
Referenced by atomic_shared_ptr< T >::_scan_(), atomic_shared_ptr< T >::compareAndSwap(), and atomic_shared_ptr< T >::swap().
template<typename T> Refcnt atomic_shared_ptr< T >::_refcnt () const [inline, private]
Local (temporary) reference counter. Local reference counter is a trick to tell the observation to other threads.
Definition at line 186 of file atomic_smart_ptr.h.
Referenced by atomic_shared_ptr< T >::_leave_scan_(), atomic_shared_ptr< T >::_reserve_scan_(), atomic_shared_ptr< T >::compareAndSwap(), and atomic_shared_ptr< T >::swap().
The documentation for this class was generated from the following file:
kame/atomic_smart_ptr.h