KAME2: XTalker< tArg > Class Template Reference
XTalker< tArg > Class Template Reference
#include <xsignal.h>
Detailed Description
template<class tArg>
class XTalker< tArg >
M/M Listener and Talker model
See also:
XListener, XSignalStore tArg: value which will be derivered tArgWrapper: copied argument, will be released by GC someday
Definition at line 94 of file xsignal.h.
Public Member Functions
shared_ptr< XListener > connectStatic (void(*func)(const tArg &), int flags=0)
template<class tObj, class tClass>
shared_ptr< XListener > connectWeak (const shared_ptr< tObj > &obj, void(tClass::*func)(const tArg &), int flags=0)
template<class tObj, class tClass>
shared_ptr< XListener > connectShared (const shared_ptr< tObj > &obj, void(tClass::*func)(const tArg &), int flags=0)
void connect (const shared_ptr< XListener > &)
void disconnect (const shared_ptr< XListener > &)
void talk (const tArg &arg)
bool empty () const
Private Types
typedef _XListenerImpl< tArg > Listener
typedef std::deque< weak_ptr
< Listener > > ListenerList
typedef ListenerList::iterator ListenerList_it
typedef
ListenerList::const_iterator ListenerList_const_it
Private Member Functions
void connect (const shared_ptr< Listener > &)
Private Attributes
atomic_shared_ptr< ListenerList > m_listeners
listener list is atomically substituted by new one. i.e. Read-Copy-Update.
Classes
struct Transaction
struct TransactionAllowDup
struct TransactionAvoidDup
Member Function Documentation
template<class tArg> shared_ptr< XListener > XTalker< tArg >::connectStatic (void(*)(const tArg &) func, int flags = 0) [inline]
Associate XTalker to XListener Talker will call user member function of listener. This function can be called over once.
See also:
disconnect(), mask(), unmask() XListener holds a pointer of a static function
Parameters:
func a pointer to static function
flags
See also:
XListener::FLAGS
Returns:
shared_ptr to XListener.
Definition at line 192 of file xsignal.h.
template<class tArg> template<class tObj, class tClass> shared_ptr< XListener > XTalker< tArg >::connectWeak (const shared_ptr< tObj > & obj, void(tClass::*)(const tArg &) func, int flags = 0) [inline]
Associate XTalker to XListener Talker will call user member function of listener. This function can be called over once.
See also:
disconnect(), mask(), unmask() XListener holds weak_ptr() of the instance
Parameters:
obj a pointer to object
func a pointer to member function
flags
See also:
XListener::FLAGS
Returns:
shared_ptr to XListener.
Definition at line 215 of file xsignal.h.
template<class tArg> template<class tObj, class tClass> shared_ptr< XListener > XTalker< tArg >::connectShared (const shared_ptr< tObj > & obj, void(tClass::*)(const tArg &) func, int flags = 0) [inline]
Associate XTalker to XListener Talker will call user member function of listener. This function can be called over once.
See also:
disconnect(), mask(), unmask() XListener holds shared_ptr() of the instance
Parameters:
obj a pointer to object
func a pointer to member function
flags
See also:
XListener::FLAGS
Returns:
shared_ptr to XListener.
Definition at line 203 of file xsignal.h.
template<class tArg> void XTalker< tArg >::talk (const tArg & arg) [inline]
Request a talk to connected listeners. If a listener is not mainthread model, the listener will be called later.
Parameters:
arg passing argument to all listeners If listener avoids duplication, lock won't be passed to listener.
Definition at line 272 of file xsignal.h.
References atomic_scoped_ptr< T >::get(), XTalker< tArg >::m_listeners, XKameError::print(), and atomic_scoped_ptr< T >::swap().
Referenced by XNode::disable(), XDriver::finishRecordingNReadLock(), XNode::setUIEnabled(), XNode::touch(), and XGraph::unlock().
The documentation for this class was generated from the following file:
kame/xsignal.h