KAME2: XNode Class Reference
XNode Class Reference
#include <xnode.h>
Detailed Description
XNode supports load/save for scripts/GUI, and signaling among threads.
See also:
create(), createOrphan()
Definition at line 203 of file transaction.h.
Public Types
typedef std::deque< shared_ptr
< XNode > > NodeList
Public Member Functions
template<class T>
shared_ptr< T > create (const char *name, bool runtime=false)
template<class T, typename X>
shared_ptr< T > create (const char *name, bool runtime, X x)
template<class T, typename X, typename Y>
shared_ptr< T > create (const char *name, bool runtime, X x, Y y)
template<class T, typename X, typename Y, typename Z>
shared_ptr< T > create (const char *name, bool runtime, X x, Y y, Z z)
template<class T, typename X, typename Y, typename Z, typename ZZ>
shared_ptr< T > create (const char *name, bool runtime, X x, Y y, Z z, ZZ zz)
XString getName () const
virtual XString getLabel () const
XString getTypename () const
shared_ptr< XNode > getChild (const XString &var) const
shared_ptr< XNode > getParent () const
atomic_shared_ptr< const NodeList > children () const
void clearChildren ()
int releaseChild (const shared_ptr< XNode > &node)
bool isRunTime () const
bool isUIEnabled () const
void setUIEnabled (bool v)
Enable/Disable control over GUI.
void disable ()
Disable all operations on this node forever.
void touch ()
Touch signaling.
XTalker< shared_ptr< XNode > > & onTouch ()
XTalker< shared_ptr< XNode > > & onUIEnabled ()
virtual void insert (const shared_ptr< XNode > &ptr)
Protected Member Functions
XNode (const char *name, bool runtime=false)
Use XNODE_OBJECT macro in sub-classes.
bool isEnabled () const
If false, all operations have to be disabled.
Protected Attributes
atomic_shared_ptr< NodeList > m_children
XTalker< shared_ptr< XNode > > m_tlkOnTouch
XTalker< shared_ptr< XNode > > m_tlkOnUIEnabled
Private Types
enum { FLAG_RUNTIME = 0x1, FLAG_ENABLED = 0x2, FLAG_UI_ENABLED = 0x4 }
typedef std::deque< shared_ptr
< XNode > > NodeList
Private Attributes
Transactional< Property > m_property
const XString m_name
int m_flags
weak_ptr< XNode > m_parent
Static Private Attributes
static XThreadLocal< NodeList > stl_thisCreating
Classes
struct Property
Member Function Documentation
XString XNode::getName () const
Returns:
internal/script name. Use latin1 chars.
Definition at line 37 of file xnode.cpp.
Referenced by getLabel(), XSecondaryDriver::onConnectedRecorded(), and XNode().
virtual XString XNode::getLabel () const [inline, virtual]
Returns:
i18n name for UI.
Reimplemented in XInterface, and XGraph.
Definition at line 71 of file xnode.h.
References getName().
Referenced by XSecondaryDriver::onConnectedRecorded(), and XPulser::onPulseChanged().
atomic_shared_ptr<const NodeList> XNode::children () const [inline]
Returns:
null if node has no child.
Definition at line 79 of file xnode.h.
Referenced by XGraph::setupRedraw(), and XMeasure::stop().
bool XNode::isUIEnabled () const [inline]
If true, operation allowed by GUI
See also:
SetUIEnabled()
Definition at line 88 of file xnode.h.
XTalker<shared_ptr<XNode> >& XNode::onTouch () [inline]
After touching
See also:
touch()
Definition at line 98 of file xnode.h.
Referenced by touch().
XTalker<shared_ptr<XNode> >& XNode::onUIEnabled () [inline]
If true, operation allowed by GUI
See also:
setUIEnabled
Definition at line 101 of file xnode.h.
Referenced by disable(), and setUIEnabled().
The documentation for this class was generated from the following files:
kame/transaction.h
kame/xnode.h
kame/xnode.cpp